id: d6_zhilagg_settings
label: Zhilagg configuration
migration_tags:
  - Drupal 6
source:
  plugin: variable
  variables:
    - zhilagg_fetcher
    - zhilagg_parser
    - zhilagg_processors
    - zhilagg_allowed_html_tags
    - zhilagg_teaser_length
    - zhilagg_clear
    - zhilagg_summary_items
process:
  fetcher: zhilagg_fetcher
  parser: zhilagg_parser
  processors: zhilagg_processors
  'items/allowed_html': zhilagg_allowed_html_tags
  'items/teaser_length': zhilagg_teaser_length
  'items/expire': zhilagg_clear
  'source/list_max': zhilagg_summary_items
destination:
  plugin: config
  config_name: zhilagg.settings
